[package]
authors = ['PureStake']
build = 'build.rs'
description = 'Substrate Moonbeam Node '
edition = '2018'
homepage = 'https://moonbeam.network'
license = 'Unlicense'
name = 'node-moonbeam'
repository = 'https://github.com/PureStake/moonbeam/'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
futures = '0.3.4'
log = '0.4.8'
structopt = '0.3.8'
jsonrpc-core = '14.0.3'

[dependencies.node-moonbeam-runtime]
path = '../runtime'
version = '0.1.0'

[dependencies.sc-basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-cli]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-client-api]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-consensus]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-consensus-babe]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-finality-grandpa]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-network]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-service]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-rpc]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sp-consensus]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sp-consensus-babe]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sp-finality-grandpa]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sp-inherents]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sp-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.pallet-transaction-payment-rpc]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.substrate-frame-rpc-system]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-consensus-babe-rpc]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sc-authority-discovery]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.sp-authority-discovery]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.pallet-authority-discovery]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.pallet-im-online]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.frame-support]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.node-primitives]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[build-dependencies.substrate-build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'

[dependencies.evm]
git = 'https://github.com/paritytech/substrate.git'
rev = '45b9f0a9cbf901abaa9f1fca5fe8baeed029133d'
default-features = false
package = 'pallet-evm'

[[bin]]
name = 'node-moonbeam'
