[package]
name = "precompiles"
version = "0.1.0"
authors = ["Samer Afach <info@afach.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
hex-literal = "0.3.1"

sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }

sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-evm = { git = "https://github.com/purestake/substrate", default-features = false, branch = "tgmichel-rococo-branch" }

[features]
default = [ "std" ]
std = [
#	"serde",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"sp-offchain/std",
	"sp-session/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	"sp-inherents/std",
#	"frame-support/std",
#	"frame-executive/std",
#	"frame-system/std",
#	"pallet-balances/std",
#	"pallet-randomness-collective-flip/std",
#	"pallet-timestamp/std",
#	"pallet-sudo/std",
#	"pallet-transaction-payment/std",
#	"parachain-info/std",
#	"cumulus-runtime/std",
#	"cumulus-parachain-upgrade/std",
#	"cumulus-message-broker/std",
#	"cumulus-upward-message/std",
#	"cumulus-primitives/std",
#	"cumulus-token-dealer/std",
#	"ethereum/std",
#	"pallet-evm/std",
#	"frontier-rpc-primitives/std",
#	"frame-system-rpc-runtime-api/std",
#	"pallet-transaction-payment-rpc-runtime-api/std",
]

