name: Release

on: [push]

env:
  WASM_BUILD_TOOLCHAIN: nightly-2020-05-14

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Cache Rust dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ env.WASM_BUILD_TOOLCHAIN }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build--${{ env.WASM_BUILD_TOOLCHAIN }}
    - uses: actions-rs/toolchain@v1
      with:
        target: wasm32-unknown-unknown
        toolchain: ${{ env.WASM_BUILD_TOOLCHAIN }}
        default: true
    - name: Build
      run: cargo build --release --verbose --all
    - name: Upload moonbase-alphanet node
      uses: actions/upload-artifact@v2
      with:
        name: moonbase-alphanet
        path: target/release/moonbase-alphanet

  generate-specs:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: moonbase-alphanet
        path: moonbase-alphanet
    - name: Generate specs
      run: pwd
    - name: Generate specs
      run: PARACHAIN_BINARY=/home/runner/work/moonbeam/moonbeam/moonbase-alphanet scripts/generate-parachain-specs.sh
    - name: Upload parachain spec plain
      uses: actions/upload-artifact@v2
      with:
        name: moonbase-alphanet-specs-plain.json
        path: build/alphanet/moonbase-alphanet-specs-plain.json
    - name: Upload parachain spec raw
      uses: actions/upload-artifact@v2
      with:
        name: moonbase-alphanet-specs-raw.json
        path: build/alphanet/moonbase-alphanet-specs-raw.json
    - name: Upload parachain wasm
      uses: actions/upload-artifact@v2
      with:
        name: parachain-runtime.wasm
        path: build/alphanet/parachain.wasm
    - name: Upload parachain genesis state
      uses: actions/upload-artifact@v2
      with:
        name: parachain-genesis.txt
        path: build/alphanet/parachain.genesis

