name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Cache Rust dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
    - name: Info on cache
      run: echo "Hitting the cache? $CACHE_HIT"
      env:
        CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}
    - name: Init
      run: |
        scripts/init.sh
        cargo --version
        rustc --version
        cargo +$WASM_BUILD_TOOLCHAIN --version
        rustc +$WASM_BUILD_TOOLCHAIN --version
      env:
        WASM_BUILD_TOOLCHAIN: nightly-2020-05-14
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all
